# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/')),
                ('kind', models.CharField(blank=True, default='', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rfq.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
