# Generated by Django 5.0.14 on 2026-02-06 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAccess',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('requested_items', models.JSONField(default=list)),
                ('submission_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='sent', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_accesses', to='rfq.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
