# Generated by Django 5.0.14 on 2026-02-06 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0003_supplieraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraccess',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='approved_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplieraccess',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('re_quote_requested', 'Re-quote Requested'), ('rejected', 'Rejected'), ('lost', 'Lost'), ('expired', 'Expired')], default='sent', max_length=32),
        ),
        migrations.CreateModel(
            name='SupplierAccessRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('requested_items', models.JSONField(default=list)),
                ('submission_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_decision', models.CharField(blank=True, max_length=32, null=True)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('decision_by', models.CharField(blank=True, max_length=150, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rfq.supplieraccess')),
            ],
            options={
                'ordering': ['round'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInteractionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('file', models.FileField(upload_to='interaction_files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='rfq.supplieraccess')),
            ],
        ),
    ]
