# Generated by Django 5.2.9 on 2026-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0004_supplieraccess_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraccess',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='supplieraccess',
            name='instruction_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
