# Generated by Django 5.2.9 on 2026-02-09 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0005_supplieraccess_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('received_from', models.CharField(blank=True, default='', max_length=255)),
                ('quote_number', models.CharField(max_length=128, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateField()),
                ('expire_preset', models.IntegerField(blank=True, choices=[(30, '30 days'), (60, '60 days'), (90, '90 days'), (120, '120 days'), (360, '360 days')], null=True)),
                ('currency', models.CharField(blank=True, default='EUR', max_length=10)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incoterm', models.CharField(blank=True, default='', max_length=50)),
                ('mov', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum Order Value', max_digits=12, null=True)),
                ('extra_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('packaging', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quotes/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('supplier_portal', 'Supplier Portal'), ('email', 'Email'), ('import', 'Import')], default='manual', max_length=32)),
                ('source_id', models.CharField(blank=True, default='', help_text='SupplierAccess ID pokud ze Supplier Portalu', max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='rfq.project')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('mpn', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('uom', models.CharField(blank=True, default='pcs', max_length=20)),
                ('moq', models.IntegerField(default=1)),
                ('manufacturing_lead_time', models.CharField(blank=True, default='', max_length=100)),
                ('supplier_lead_time', models.CharField(blank=True, default='14 days', max_length=100)),
                ('available_stock', models.IntegerField(blank=True, null=True)),
                ('available_stock_date', models.DateField(blank=True, null=True)),
                ('qty_1', models.CharField(blank=True, default='', max_length=50)),
                ('price_1', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_2', models.CharField(blank=True, default='', max_length=50)),
                ('price_2', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_3', models.CharField(blank=True, default='', max_length=50)),
                ('price_3', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_4', models.CharField(blank=True, default='', max_length=50)),
                ('price_4', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_5', models.CharField(blank=True, default='', max_length=50)),
                ('price_5', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_6', models.CharField(blank=True, default='', max_length=50)),
                ('price_6', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_7', models.CharField(blank=True, default='', max_length=50)),
                ('price_7', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_8', models.CharField(blank=True, default='', max_length=50)),
                ('price_8', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_9', models.CharField(blank=True, default='', max_length=50)),
                ('price_9', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('qty_10', models.CharField(blank=True, default='', max_length=50)),
                ('price_10', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('line_number', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rfq.quote')),
            ],
            options={
                'ordering': ['line_number', 'id'],
            },
        ),
    ]
